spring:
  profiles:
    active: local # 디폴트 환경
  messages:
    basename: i18n/exception
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: create
      format_sql: true
    showSql: true
    generate-ddl: true
  jwt:
    secret: govlepel@$&
  h2:
    console:
      enabled: true
server:
  port: 3000
